PACKAGE_NAME="odl-tb5"
PACKAGE_VERSION="@PROJECT_VERSION@"
AUTOINSTALL="yes"

BUILT_MODULE_NAME[0]="odl_tb5"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make CC=$(command -v gcc-15 || command -v gcc-14 || echo gcc) -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
